### ISSUE TITLE
I press F5 and start page load correctly.

### ISSUE THREAD

**Issue by gianlucavagnuzzi** [hokkaidoperson/DokuWiki-WikiFormatStyling-Plugin#3]
Hi to all.
Dokuwiki version: version-2022-07-31a

After restart docker, first time i visit dokuwiki appear error:

**502 Bad Gateway
nginx/1.20.2**

I press F5 and start page load correctly.

it's seems depend Wiki-Style Script extension

There are this error in nginx error log:
`2023/02/06 07:26:38 [error] 312#312: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins/wikiformatstyling/syntax/nwtag.php on line 48PHP message: PHP Warning:  Trying to access array offset on value of type null in /config/dokuwiki/lib/plugins
2023/02/06 07:26:38 [error] 312#312: *1 upstream sent too big header while reading response header from upstream, client: 172.21.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "wiki.localdomain:8180"`

**Comment by fiwswe** [comment]
I would recommend changing the title of this issue. The PHP warnings are the cause of the 502, not the other way around and the 502 is highly dependent on your specific hosting environment, while the PHP warnings will happen anywhere.

> I press F5 and start page load correctly.

Probably because of the DokuWiki cache. Try adding `&purge=true` to the URL and observe error reappearing ;-)
(See: https://www.dokuwiki.org/?id=devel:caching)

I suspect you are using PHP 8.x but it would be good if you could state the actual PHP version.

That said, I don't use this plugin, so I will not be of much help solving the problems.

**Comment by gianlucavagnuzzi** [comment]
> 

Thanks, i have changed title

Dokuwiki is in docker.
Php version is:
```
root@03f0714d579c:/# php -v
PHP 8.1.14 (cli) (built: Jan  6 2023 14:49:32) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.14, Copyright (c) Zend Technologies
```

**Comment by fiwswe** [comment]
> Thanks, i have changed title

Sorry, but good grief! Why does your new title describe something that has nothing to do with the issue? A **good** title should give a brief synopsis of the issue. Yours is even more off-topic than the original one. Someone reading your title will think: „Great, there is no problem. I don't need to waste time reading the details of this issue.“

> Dokuwiki is in docker.

True but probably irrelevant.



> Php version is:

Note: The PHP version used on the command line is not always the one used in a web application. In your case it is very likely not an issue but in general this can not be assumed. I administer various machines where multiple PHP versions are installed and different websites even use different PHP versions, not to mention command line scripts.

You can determine the actual running PHP version used by DokuWiki by (temporarily) turning on the [allowdebug](https://www.dokuwiki.org/config:allowdebug) setting and then adding `&do=debug` to the URL. Then look for the heading „PHP Version“.

**Comment by gianlucavagnuzzi** [comment]
> > Thanks, i have changed title
> 
> Sorry, but good grief! Why does your new title describe something that has nothing to do with the issue? A **good** title should give a brief synopsis of the issue. Yours is even more off-topic than the original one. Someone reading your title will think: „Great, there is no problem. I don't need to waste time reading the details of this issue.“
> 
> > Dokuwiki is in docker.
> 
> True but probably irrelevant.
> 
> > Php version is:
> 
> Note: The PHP version used on the command line is not always the one used in a web application. In your case it is very likely not an issue but in general this can not be assumed. I administer various machines where multiple PHP versions are installed and different websites even use different PHP versions, not to mention command line scripts.
> 
> You can determine the actual running PHP version used by DokuWiki by (temporarily) turning on the [allowdebug](https://www.dokuwiki.org/config:allowdebug) setting and then adding `&do=debug` to the URL. Then look for the heading „PHP Version“.

thanks very much for all help!! i will close issue and reopen new more do better issue! :)
